Add Gyro Subsystem
FRC5113/2023-Pandemonium pull request #10
Opened 2023-02-13 22:49 UTC by KevinH45

Added a separate gyro subsystem per today's meeting. Implements library's SmartSubsystem.

No commands.

2023-02-14 02:26 UTC, drvladb requested changes
Would recommend using readPeriodicOutput and caching gyro state using variables.

2023-02-16 05:07 UTC, KevinH45 commented
changes requested should be fixed by commit 6b77e9f.

2023-02-16 19:27 UTC, jrego05 reviewed
Looks good
\- Totally Jack

2023-02-16 19:27 UTC, jrego05 approved these changes

2023-02-16 19:28 UTC, merged